import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          Landing(),
        ]),
      ),
    );
  }
}

class Landing extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 1920,
          height: 1080,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(color: Colors.white),
          child: Stack(
            children: [
              Positioned(
                left: 411,
                top: 516,
                child: Text(
                  'Government Engineering College Chamarajanagara',
                  textAlign: TextAlign.center,
                  style: TextStyle(
                    color: const Color(0xFF3B38A0),
                    fontSize: 40,
                    fontFamily: 'Montserrat',
                    fontWeight: FontWeight.w800,
                  ),
                ),
              ),
              Positioned(
                left: 735,
                top: 445,
                child: Text(
                  'Student database management system for',
                  textAlign: TextAlign.center,
                  style: TextStyle(
                    color: const Color(0xFF3B38A0),
                    fontSize: 20,
                    fontFamily: 'Montserrat',
                    fontWeight: FontWeight.w700,
                  ),
                ),
              ),
              Positioned(
                left: 880,
                top: 616,
                child: Container(
                  width: 160,
                  height: 48,
                  decoration: ShapeDecoration(
                    color: const Color(0xFF1A2A80),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(15),
                    ),
                    shadows: [
                      BoxShadow(
                        color: Color(0x3F000000),
                        blurRadius: 6,
                        offset: Offset(0, 5),
                        spreadRadius: 0,
                      )
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 923,
                top: 625,
                child: Text(
                  'log-in',
                  textAlign: TextAlign.center,
                  style: TextStyle(
                    color: Colors.white,
                    fontSize: 24,
                    fontFamily: 'Montserrat',
                    fontWeight: FontWeight.w800,
                  ),
                ),
              ),
              Positioned(
                left: -129,
                top: -170,
                child: Container(
                  width: 340,
                  height: 340,
                  decoration: ShapeDecoration(
                    shape: OvalBorder(
                      side: BorderSide(
                        width: 10,
                        color: const Color(0xFF7A85C1),
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 1479,
                top: 654,
                child: Container(
                  width: 682,
                  height: 682,
                  decoration: ShapeDecoration(
                    shape: OvalBorder(
                      side: BorderSide(
                        width: 10,
                        color: const Color(0xFF7A85C1),
                      ),
                    ),
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}