import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          Login(),
        ]),
      ),
    );
  }
}

class Login extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 1920,
          height: 1080,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(color: Colors.white),
          child: Stack(
            children: [
              Positioned(
                left: 578,
                top: 460,
                child: Container(
                  width: 763,
                  height: 77,
                  decoration: ShapeDecoration(
                    color: const Color(0x7FB2B0E8),
                    shape: RoundedRectangleBorder(
                      side: BorderSide(
                        width: 1,
                        color: Colors.black.withValues(alpha: 0.50),
                      ),
                      borderRadius: BorderRadius.circular(15),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 578,
                top: 591,
                child: Container(
                  width: 763,
                  height: 77,
                  decoration: ShapeDecoration(
                    color: const Color(0x7FB2B0E8),
                    shape: RoundedRectangleBorder(
                      side: BorderSide(
                        width: 1,
                        color: Colors.black.withValues(alpha: 0.50),
                      ),
                      borderRadius: BorderRadius.circular(15),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 578,
                top: 729,
                child: Container(
                  width: 763,
                  height: 77,
                  decoration: ShapeDecoration(
                    color: const Color(0xFF1A2A80),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(15),
                    ),
                    shadows: [
                      BoxShadow(
                        color: Color(0x3F000000),
                        blurRadius: 10.60,
                        offset: Offset(0, 4),
                        spreadRadius: 0,
                      )
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 867,
                top: 487,
                child: Text(
                  'Enter your login ID',
                  textAlign: TextAlign.center,
                  style: TextStyle(
                    color: Colors.black,
                    fontSize: 20,
                    fontFamily: 'Montserrat',
                    fontWeight: FontWeight.w300,
                  ),
                ),
              ),
              Positioned(
                left: 858,
                top: 618,
                child: Text(
                  'Enter your password',
                  textAlign: TextAlign.center,
                  style: TextStyle(
                    color: Colors.black,
                    fontSize: 20,
                    fontFamily: 'Montserrat',
                    fontWeight: FontWeight.w300,
                  ),
                ),
              ),
              Positioned(
                left: 918,
                top: 749,
                child: Text(
                  'login',
                  textAlign: TextAlign.center,
                  style: TextStyle(
                    color: Colors.white,
                    fontSize: 30,
                    fontFamily: 'Montserrat',
                    fontWeight: FontWeight.w900,
                  ),
                ),
              ),
              Positioned(
                left: 863,
                top: 198,
                child: Container(
                  width: 194,
                  height: 194,
                  child: Stack(),
                ),
              ),
              Positioned(
                left: 815,
                top: 867,
                child: Text(
                  'forgot password? click here to reset.',
                  textAlign: TextAlign.center,
                  style: TextStyle(
                    color: Colors.black,
                    fontSize: 16,
                    fontFamily: 'Montserrat',
                    fontWeight: FontWeight.w400,
                  ),
                ),
              ),
              Positioned(
                left: -361,
                top: -290,
                child: Container(
                  width: 682,
                  height: 682,
                  decoration: ShapeDecoration(
                    shape: OvalBorder(
                      side: BorderSide(
                        width: 10,
                        color: const Color(0xFF7A85C1),
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 1695,
                top: 867,
                child: Container(
                  width: 398,
                  height: 398,
                  decoration: ShapeDecoration(
                    shape: OvalBorder(
                      side: BorderSide(
                        width: 10,
                        color: const Color(0xFF7A85C1),
                      ),
                    ),
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}