import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          Hod(),
        ]),
      ),
    );
  }
}

class Hod extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 1920,
          height: 1080,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(color: Colors.white),
          child: Stack(
            children: [
              Positioned(
                left: 164,
                top: 34,
                child: Text(
                  'HOD',
                  textAlign: TextAlign.center,
                  style: TextStyle(
                    color: const Color(0xFF1A2A80),
                    fontSize: 50,
                    fontFamily: 'Montserrat',
                    fontWeight: FontWeight.w900,
                  ),
                ),
              ),
              Positioned(
                left: 563,
                top: 166,
                child: Container(
                  width: 386,
                  height: 394,
                  decoration: ShapeDecoration(
                    color: const Color(0xFF7A85C1),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(44),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 997,
                top: 166,
                child: Container(
                  width: 788,
                  height: 240,
                  decoration: ShapeDecoration(
                    color: const Color(0xFF7A85C1),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(15),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 563,
                top: 580,
                child: Container(
                  width: 386,
                  height: 394,
                  decoration: ShapeDecoration(
                    color: const Color(0xFF7A85C1),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(44),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 997,
                top: 444,
                child: Container(
                  width: 361,
                  height: 536,
                  decoration: ShapeDecoration(
                    color: const Color(0xFF7A85C1),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(44),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 1398,
                top: 444,
                child: Container(
                  width: 387,
                  height: 536,
                  decoration: ShapeDecoration(
                    color: const Color(0xFF7A85C1),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(44),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: 149,
                child: Container(
                  width: 452,
                  height: 931,
                  decoration: ShapeDecoration(
                    color: const Color(0xFF1A2A80),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.only(topRight: Radius.circular(30)),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: 225,
                child: Container(
                  width: 398,
                  height: 68,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 398,
                          height: 68,
                          decoration: ShapeDecoration(
                            color: const Color(0xFFF1F1F1),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.only(
                                topLeft: Radius.circular(4),
                                topRight: Radius.circular(34),
                                bottomRight: Radius.circular(34),
                              ),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 90,
                        top: 22,
                        child: Text(
                          'Faculty Management',
                          textAlign: TextAlign.center,
                          style: TextStyle(
                            color: Colors.black,
                            fontSize: 20,
                            fontFamily: 'Montserrat',
                            fontWeight: FontWeight.w500,
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: 313,
                child: Container(
                  width: 398,
                  height: 68,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 398,
                          height: 68,
                          decoration: ShapeDecoration(
                            color: const Color(0xFFF2F2F2),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.only(
                                topRight: Radius.circular(34),
                                bottomRight: Radius.circular(34),
                              ),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 14,
                        top: 22,
                        child: Text(
                          'Student Overview and Management',
                          textAlign: TextAlign.center,
                          style: TextStyle(
                            color: Colors.black,
                            fontSize: 20,
                            fontFamily: 'Montserrat',
                            fontWeight: FontWeight.w500,
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: 401,
                child: Container(
                  width: 398,
                  height: 68,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 398,
                          height: 68,
                          decoration: ShapeDecoration(
                            color: const Color(0xFFF2F2F2),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.only(
                                topRight: Radius.circular(34),
                                bottomRight: Radius.circular(34),
                              ),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 20,
                        top: 22,
                        child: Text(
                          'Academic Performance Monitoring',
                          textAlign: TextAlign.center,
                          style: TextStyle(
                            color: Colors.black,
                            fontSize: 20,
                            fontFamily: 'Montserrat',
                            fontWeight: FontWeight.w500,
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: 489,
                child: Container(
                  width: 398,
                  height: 68,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 398,
                          height: 68,
                          decoration: ShapeDecoration(
                            color: const Color(0xFFF2F2F2),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.only(
                                topRight: Radius.circular(34),
                                bottomRight: Radius.circular(34),
                              ),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 80,
                        top: 22,
                        child: Text(
                          'Attendance Monitoring',
                          textAlign: TextAlign.center,
                          style: TextStyle(
                            color: Colors.black,
                            fontSize: 20,
                            fontFamily: 'Montserrat',
                            fontWeight: FontWeight.w500,
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: 577,
                child: Container(
                  width: 398,
                  height: 68,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 398,
                          height: 68,
                          decoration: ShapeDecoration(
                            color: const Color(0xFFF2F2F2),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.only(
                                topRight: Radius.circular(34),
                                bottomRight: Radius.circular(34),
                              ),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 62,
                        top: 22,
                        child: Text(
                          'Timetable and Scheduling',
                          textAlign: TextAlign.center,
                          style: TextStyle(
                            color: Colors.black,
                            fontSize: 20,
                            fontFamily: 'Montserrat',
                            fontWeight: FontWeight.w500,
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: 665,
                child: Container(
                  width: 398,
                  height: 68,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 398,
                          height: 68,
                          decoration: ShapeDecoration(
                            color: const Color(0xFFF2F2F2),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.only(
                                topRight: Radius.circular(34),
                                bottomRight: Radius.circular(34),
                              ),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 22,
                        child: Text(
                          ' Communication and Announcements',
                          textAlign: TextAlign.center,
                          style: TextStyle(
                            color: Colors.black,
                            fontSize: 20,
                            fontFamily: 'Montserrat',
                            fontWeight: FontWeight.w500,
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: 753,
                child: Container(
                  width: 398,
                  height: 68,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 398,
                          height: 68,
                          decoration: ShapeDecoration(
                            color: const Color(0xFFF2F2F2),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.only(
                                topRight: Radius.circular(34),
                                bottomRight: Radius.circular(34),
                              ),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 50,
                        top: 22,
                        child: Text(
                          'Reports and Documentation',
                          textAlign: TextAlign.center,
                          style: TextStyle(
                            color: Colors.black,
                            fontSize: 20,
                            fontFamily: 'Montserrat',
                            fontWeight: FontWeight.w500,
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: 841,
                child: Container(
                  width: 398,
                  height: 68,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 398,
                          height: 68,
                          decoration: ShapeDecoration(
                            color: const Color(0xFFF2F2F2),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.only(
                                topRight: Radius.circular(34),
                                bottomRight: Radius.circular(34),
                              ),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 68,
                        top: 22,
                        child: Text(
                          'Feedback and Evaluation',
                          textAlign: TextAlign.center,
                          style: TextStyle(
                            color: Colors.black,
                            fontSize: 20,
                            fontFamily: 'Montserrat',
                            fontWeight: FontWeight.w500,
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 1062,
                top: 65,
                child: Text(
                  'HOD PROFILE',
                  textAlign: TextAlign.center,
                  style: TextStyle(
                    color: const Color(0xFF1A2A80),
                    fontSize: 35,
                    fontFamily: 'Montserrat',
                    fontWeight: FontWeight.w900,
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}